name: Fortran Compiler Tester CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test_fpm:
    name: ${{ matrix.project.name }}_${{ matrix.os }}_${{ matrix.compiler }}_fpm
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        project:
          - name: json-fortran
        include:
          - {os: ubuntu-latest,  compiler: gfortran,  compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: ubuntu-latest,  compiler: ifx,       compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: "-fpp"}
          - {os: ubuntu-latest,  compiler: flang-new, compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: ubuntu-latest,  compiler: nvfortran, compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: ubuntu-latest,  compiler: lfortran,  compiler-version: "", extra-packages: "", fpm-version: "0.12.0", fpm-flag: "--cpp"}

          - {os: windows-latest, compiler: gfortran,  compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: windows-latest, compiler: ifx,       compiler-version: "", extra-packages: "", fpm-version: "0.12.0", fpm-flag: "/fpp"}
          - {os: windows-latest, compiler: flang-new, compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: windows-latest, compiler: lfortran,  compiler-version: "", extra-packages: "", fpm-version: "0.12.0", fpm-flag: "--cpp"}

          - {os: macos-latest,   compiler: gfortran,  compiler-version: "", extra-packages: "", fpm-version: "",       fpm-flag: ""}
          - {os: macos-latest,   compiler: lfortran,  compiler-version: "", extra-packages: "", fpm-version: "0.12.0", fpm-flag: "--cpp"}

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v6
        with:
          repository: jacobwilliams/${{ matrix.project.name }}
          path: ${{ matrix.project.name }}

      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          compiler-version: ${{ matrix.compiler-version }}
          extra-packages: ${{ matrix.extra-packages }}
          fpm-version: ${{ matrix.fpm-version }}
          checkout-repo: false

      - name: fpm build debug
        if: always()
        working-directory: ${{ matrix.project.name }}
        run: fpm build --profile debug --flag "${{ matrix.fpm-flag }}" --verbose

      - name: fpm build release
        if: always()
        working-directory: ${{ matrix.project.name }}
        run: fpm build --profile release --flag "${{ matrix.fpm-flag }}" --verbose

      - name: fpm test debug
        if: always()
        working-directory: ${{ matrix.project.name }}
        run: fpm test --profile debug --flag "${{ matrix.fpm-flag }}" --verbose

      - name: fpm test release
        if: always()
        working-directory: ${{ matrix.project.name }}
        run: fpm test --profile release --flag "${{ matrix.fpm-flag }}" --verbose