name: Setup Fortran Conda CI/CD

on: [push]
permissions:
  contents: write
jobs:
  test_fpm:
    name: ${{ matrix.os }}_${{ matrix.compiler }}_fpm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compiler: [gfortran, ifx, lfortran, flang-new, nvfortran]
        exclude:
          - {os: macos-latest,   compiler: flang-new}
          - {os: macos-latest,   compiler: ifx}
          - {os: macos-latest,   compiler: nvfortran}
          - {os: windows-latest, compiler: nvfortran}
    steps:
      - name: Setup Fortran
        uses: gha3mi/setup-fortran-conda@latest
        with:
          compiler: ${{ matrix.compiler }}
          platform: ${{ matrix.os }}

      - name: Checkout code
        run: |
          conda install git -y
          git clone https://github.com/jacobwilliams/json-fortran.git
              
      - name: fpm test (debug)
        run: |
          pwd
          cd json-fortran
          fpm test --compiler ${{ matrix.compiler }} --profile debug

      - name: fpm test (release)
        run: |
          pwd
          cd json-fortran
          fpm test --compiler ${{ matrix.compiler }} --profile release